# google_mlkit_text_recognition only bundles the Latin model; the plugin still
# references the optional CJK/Devanagari recognizers, so silence R8 about them.
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions

# flutter_gemma: MediaPipe references optional profiling/template protos that
# tasks-genai doesn't ship; safe to suppress (generated by R8 missing_rules).
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate

# flutter_gemma / MediaPipe GenAI: optional proto + profiler classes are not
# bundled; keep the frameworks intact and silence R8 about the missing refs
# (per the flutter_gemma README's ProGuard guidance).
-dontwarn com.google.mediapipe.proto.**
-keep class com.google.mediapipe.** { *; }
-keep class com.google.protobuf.** { *; }
-keep class com.google.ai.edge.** { *; }
-keep class dev.flutterberlin.flutter_gemma.** { *; }
