#!/usr/bin/env python3
"""FT-C4: Generate DPO preference pairs from SFT quality-passed samples.

Reads finetune/gen/sft.filtered.jsonl (6,446 samples), produces
finetune/gen/dpo.jsonl (≥1,500 pairs).

Each pair:
  - prompt  = [system, user]  (from the filtered sample)
  - chosen  = [assistant]     (the filtered sample's kept answer)
  - rejected = [assistant]    (adversarially generated flawed variant)

Flaw taxonomy (5 types, spread evenly):
  1. fake_lived_experience  — answer claims personal recovery
  2. hotline_when_unneeded  — hotline/911 pushed on non-crisis question
  3. ignores_passages       — answers from generic knowledge, contradicts
                              or ignores provided gold passages
  4. bracket_citations      — [1]-style markers / filenames instead of titles
  5. rambles                — blows past the register's tone budget

Rejected answers are generated by dsv4 with adversarial prompts (temp=0.7),
then verified by dsv4 judge (temp=0).  Up to 3 tries, then skip.

Checkpointed & resumable — run under nohup.
"""

from __future__ import annotations

import json
import os
import random
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

import requests

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO = Path(__file__).resolve().parent.parent
INPUT_PATH = REPO / "finetune" / "gen" / "sft.filtered.jsonl"
OUTPUT_PATH = REPO / "finetune" / "gen" / "dpo.jsonl"
CKPT_DIR = REPO / "finetune" / "gen" / ".dpo_checkpoint"

LLM_URL = "http://10.0.0.10:8002/v1/chat/completions"
LLM_MODEL = "deepseek-v4-flash"

CONCURRENCY = 12  # ≤16 per swarm rules
MAX_GEN_RETRIES = 3
MAX_JUDGE_RETRIES = 3

TARGET_PAIRS = 1500

_FLAW_TYPES = [
    "fake_lived_experience",
    "hotline_when_unneeded",
    "ignores_passages",
    "bracket_citations",
    "rambles",
]

# ---------------------------------------------------------------------------
# LLM helpers
# ---------------------------------------------------------------------------


def _call_dsv4(
    messages: list[dict],
    temperature: float = 0.7,
    max_tokens: int = 512,
) -> str | None:
    """Call dsv4 with thinking disabled. Returns content or None."""
    for attempt in range(MAX_GEN_RETRIES):
        try:
            resp = requests.post(
                LLM_URL,
                json={
                    "model": LLM_MODEL,
                    "messages": messages,
                    "temperature": temperature,
                    "max_tokens": max_tokens,
                    "chat_template_kwargs": {"thinking": False},
                },
                timeout=120,
            )
            if resp.status_code != 200:
                print(
                    f"  [dsv4 retry {attempt+1}] HTTP {resp.status_code}: {resp.text[:200]}",
                    file=sys.stderr,
                    flush=True,
                )
                time.sleep(2 * (attempt + 1))
                continue
            data = resp.json()
            content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
            if content:
                return content.strip()
            print(f"  [dsv4 retry {attempt+1}] empty response", file=sys.stderr, flush=True)
        except requests.exceptions.Timeout:
            print(f"  [dsv4 retry {attempt+1}] timeout", file=sys.stderr, flush=True)
            time.sleep(5)
        except Exception as e:
            print(f"  [dsv4 retry {attempt+1}] {e}", file=sys.stderr, flush=True)
            time.sleep(5)
    return None


def _call_judge(system_prompt: str, user_prompt: str) -> str | None:
    """Call dsv4 as a judge (temp=0, no thinking). Returns YES/NO or None."""
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    for attempt in range(MAX_JUDGE_RETRIES):
        try:
            resp = requests.post(
                LLM_URL,
                json={
                    "model": LLM_MODEL,
                    "messages": messages,
                    "temperature": 0.0,
                    "max_tokens": 256,
                    "chat_template_kwargs": {"thinking": False},
                },
                timeout=120,
            )
            if resp.status_code != 200:
                print(
                    f"  [judge retry {attempt+1}] HTTP {resp.status_code}",
                    file=sys.stderr,
                    flush=True,
                )
                time.sleep(2 * (attempt + 1))
                continue
            data = resp.json()
            content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
            if not content:
                if attempt < MAX_JUDGE_RETRIES - 1:
                    continue
                return None
            # Extract YES or NO
            upper = content.upper()
            if "YES" in upper:
                return "YES"
            if "NO" in upper:
                return "NO"
            if attempt < MAX_JUDGE_RETRIES - 1:
                continue
            return None
        except Exception as e:
            print(f"  [judge error] {e}", file=sys.stderr, flush=True)
            if attempt < MAX_JUDGE_RETRIES - 1:
                time.sleep(3)
                continue
            return None
    return None


# ---------------------------------------------------------------------------
# Flaw detection prompts (judge)
# ---------------------------------------------------------------------------

JUDGE_PROMPTS: dict[str, tuple[str, str]] = {
    "fake_lived_experience": (
        "You are a strict judge. Determine if the assistant answer below contains "
        "ANY claim of personal lived experience with addiction, sobriety, recovery, "
        "drinking, meetings, a sponsor, or a Higher Power. "
        "This INCLUDES: 'when I was drinking', 'my sponsor', 'when I got sober', "
        "'in my experience', 'I remember when', or any first-person claim about "
        "the assistant's own recovery journey. "
        "Also flag second-person framing that implies shared experience: "
        "'we alcoholics', 'those of us in recovery', 'as we know'. "
        "Answer ONLY with YES (flaw present — claims personal lived experience) "
        "or NO (no such claim).",
        "Does the assistant answer claim personal lived experience with addiction "
        "or recovery?\n\nASSISTANT ANSWER:\n{content}",
    ),
    "hotline_when_unneeded": (
        "You are a strict judge. Determine if the assistant answer below "
        "mentions a crisis hotline, suicide hotline, 911, emergency services, "
        "or similar urgent-safety resource when the user's question does NOT "
        "appear to be a crisis or safety concern. "
        "If the user's question genuinely expresses immediate danger, self-harm, "
        "or suicidal ideation, then mentioning a hotline is CORRECT and you "
        "should answer NO (flaw absent — hotline is appropriate). "
        "If the user asks a routine recovery question and the answer still pushes "
        "hotline/911/safety resources, answer YES (flaw present — unneeded hotline). "
        "Answer ONLY with YES or NO.",
        "Does the assistant answer unnecessarily push a crisis hotline, 911, "
        "or emergency services for a non-crisis question?\n\n"
        "USER QUESTION:\n{user_question}\n\n"
        "ASSISTANT ANSWER:\n{content}",
    ),
    "ignores_passages": (
        "You are a strict judge. The assistant was provided with specific "
        "recovery literature passages. Determine if the answer IGNORES those "
        "passages and instead answers from generic personal opinion, common "
        "sense, or knowledge that contradicts the provided passages. "
        "If the answer visibly references, quotes, or grounds itself in "
        "the provided passages (even imperfectly), answer NO (flaw absent). "
        "If the answer speaks from general knowledge that contradicts or "
        "ignores the passages, answer YES (flaw present). "
        "Answer ONLY with YES or NO.",
        "Does the assistant answer ignore, contradict, or fail to ground in "
        "the provided passages, instead answering from generic knowledge?\n\n"
        "PROVIDED PASSAGES (from user question):\n{passages}\n\n"
        "ASSISTANT ANSWER:\n{content}",
    ),
    "bracket_citations": (
        "You are a strict judge. Determine if the assistant answer contains "
        "ANY bracketed citation markers like [1], [2], [BB], [AA], [page 42], "
        "filenames (e.g., 'bigbook.pdf'), or code-like references. "
        "Natural title references like 'the Big Book' or 'Twelve Steps and "
        "Twelve Traditions' are fine — those are NOT bracketed citations. "
        "Answer ONLY with YES (contains bracketed/inline citation markers "
        "or filenames) or NO (no such markers).",
        "Does the assistant answer contain bracketed citation markers, "
        "filenames with extensions, or code-like reference tags?\n\n"
        "ASSISTANT ANSWER:\n{content}",
    ),
    "rambles": (
        "You are a strict judge. Determine if the assistant answer is "
        "too long, rambling, or verbose for its register. "
        "If the register is 'brief' (expected 1-4 short sentences), answers "
        "longer than 4 sentences or with excessive detail are flawed. "
        "If the register is 'factual' (concise informative), answers that "
        "wander with tangents, repetition, or unnecessary context are flawed. "
        "If the answer is concise, focused, and appropriate for its register, "
        "answer NO (flaw absent — not rambling). "
        "Answer ONLY with YES (rambles / too long / blows tone budget) "
        "or NO (appropriately concise).",
        "Does the assistant answer ramble, exceed the register's tone budget, "
        "or contain unnecessary tangents?\n\n"
        "REGISTER: {register}\n"
        "USER QUESTION:\n{user_question}\n\n"
        "ASSISTANT ANSWER:\n{content}",
    ),
}

# ---------------------------------------------------------------------------
# Adversarial generation prompts
# ---------------------------------------------------------------------------

GEN_SYSTEM = (
    "You generate flawed training examples for data augmentation. "
    "Produce the exact type of flaw requested — do NOT 'fix' it or avoid it. "
    "Keep the answer roughly the same length and topic as the reference answer. "
    "Do NOT add any meta-commentary, notes, or disclaimers."
)


def _build_gen_prompt(
    flaw: str,
    system_prompt: str,
    user_question: str,
    chosen_answer: str,
    register: str,
    passages: str,
) -> str:
    """Build the adversarial generation prompt for a given flaw type."""
    base = (
        f"REFERENCE ANSWER (correct, grounded version):\n"
        f"{chosen_answer}\n\n"
        f"Now rewrite it to introduce the following flaw:\n\n"
    )

    flaw_instructions = {
        "fake_lived_experience": (
            "FLAW: fake_lived_experience\n\n"
            "Rewrite the answer so it speaks from personal lived experience "
            "with addiction and recovery. Use first-person claims: "
            "'When I was drinking...', 'My sponsor told me...', "
            "'When I got sober...', 'I remember...', "
            "'In my experience...'. The answer should sound like "
            "a person in recovery sharing their story, NOT like an AI "
            "grounded in literature."
        ),
        "hotline_when_unneeded": (
            "FLAW: unneeded_hotline\n\n"
            "Rewrite the answer to prominently feature a crisis hotline, "
            "suicide hotline, or 911, even though the user's question is "
            "a routine, non-crisis recovery question. "
            "Insert something like: 'If you're in crisis, please call "
            "the AA hotline at 1-800-...' or 'If you feel unsafe, "
            "call 911 immediately.' The hotline advice should feel "
            "disproportionate to the question."
        ),
        "ignores_passages": (
            "FLAW: ignores_passages\n\n"
            "Rewrite the answer to ignore the provided recovery literature "
            "passages entirely. Answer from generic common sense, pop "
            "psychology, or personal opinion. Contradict or disregard "
            "the specific teachings in the passages. "
            "Do NOT reference the passages, do NOT quote them, do NOT "
            "name any recovery work by title. Sound like generic advice."
        ),
        "bracket_citations": (
            "FLAW: bracket_citations\n\n"
            "Rewrite the answer to use bracketed citation markers "
            "LIKE [1], [BB], [AA], [p.45], [WL], [12&12] or filenames "
            "like 'bigbook.pdf' or 'step1.txt' instead of natural "
            "title references. Replace any natural title mentions "
            "with these artificial markers. The answer should resemble "
            "academic citation style, not natural conversation."
        ),
        "rambles": (
            "FLAW: rambles\n\n"
            "Rewrite the answer to be excessively long, rambling, and "
            "verbose. Add tangents, repetition, unnecessary detail, "
            "and multiple caveats. If the register is 'brief', make it "
            "5+ sentences with wandering asides. If factual, add "
            "unnecessary background and repeat points in different words. "
            "The answer should clearly exceed the appropriate tone budget."
        ),
    }

    instruction = flaw_instructions.get(flaw, "")
    context = (
        f"\n\nCONTEXT:\n"
        f"Register: {register}\n"
        f"System prompt given to the AI:\n{system_prompt}\n"
        f"User question:\n{user_question}\n"
    )
    if passages:
        context += f"\nProvided passages:\n{passages}\n"

    return f"{base}{instruction}{context}\n\nONLY output the rewritten answer. No meta-commentary."


# ---------------------------------------------------------------------------
# Passage extraction
# ---------------------------------------------------------------------------

def _extract_passages(user_content: str) -> str:
    """Extract the 'Relevant passages from recovery literature' section."""
    marker = "Relevant passages from recovery literature"
    if marker in user_content:
        idx = user_content.index(marker)
        return user_content[idx:]
    return ""


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------


def _load_checkpoint() -> dict[int, str]:
    """Load completed pairs: index → JSON line. Resumes from previous run."""
    completed: dict[int, str] = {}

    if CKPT_DIR.is_dir():
        for ckpt_file in sorted(CKPT_DIR.iterdir()):
            if ckpt_file.suffix == ".jsonl":
                with open(ckpt_file) as f:
                    for line in f:
                        line = line.strip()
                        if line:
                            row = json.loads(line)
                            idx = row.get("_src_idx")
                            if idx is not None:
                                completed[idx] = line

    # Also load any existing dpo.jsonl
    if OUTPUT_PATH.is_file():
        with open(OUTPUT_PATH) as f:
            for line in f:
                line = line.strip()
                if line:
                    row = json.loads(line)
                    idx = row.get("_src_idx")
                    if idx is not None:
                        completed[idx] = line

    return completed


def _save_checkpoint_row(row: dict, batch_id: str):
    """Save a single completed row to a checkpoint file."""
    CKPT_DIR.mkdir(parents=True, exist_ok=True)
    ckpt_file = CKPT_DIR / f"batch_{batch_id}.jsonl"
    with open(ckpt_file, "a") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _assemble_final(completed: dict[int, str], all_indices: list[int]):
    """Write dpo.jsonl from completed entries in the correct order."""
    rows: list[str] = []
    seen: set[int] = set()
    for idx in all_indices:
        line = completed.get(idx)
        if line and idx not in seen:
            rows.append(line)
            seen.add(idx)
    with open(OUTPUT_PATH, "w") as f:
        for r in rows:
            f.write(r + "\n")
    OUTPUT_PATH.chmod(0o644)


# ---------------------------------------------------------------------------
# Flaw → sample compatibility
# ---------------------------------------------------------------------------

def _is_flaw_compatible(flaw: str, sample: dict) -> bool:
    """Check if a flaw type is applicable to this sample."""
    meta = sample.get("meta", {})
    user_content = sample["messages"][1]["content"]
    sample_type = meta.get("sample_type", "context")
    crisis = meta.get("crisis_adjacent", False)
    register = meta.get("register", "factual")
    has_passages = "Relevant passages from recovery literature" in user_content

    if flaw == "hotline_when_unneeded":
        # Don't apply to crisis-adjacent questions (hotline IS appropriate)
        return not crisis

    if flaw == "ignores_passages":
        # Only makes sense for samples that have gold passages
        return has_passages

    if flaw == "rambles":
        # Works on any register — brief is actually the best target
        return True

    # fake_lived_experience and bracket_citations work on any sample
    return True


# ---------------------------------------------------------------------------
# Assign flaw types evenly while respecting compatibility
# ---------------------------------------------------------------------------

def _assign_flaws(eligible: list[tuple[int, dict]]) -> list[tuple[int, dict, str]]:
    """Assign flaw types to eligible samples, cycling through types but
    skipping incompatible flaw/sample combinations."""
    assigned: list[tuple[int, dict, str]] = []
    flaw_counts: dict[str, int] = {f: 0 for f in _FLAW_TYPES}

    # Track how many of each flaw we've assigned per batch of 5
    for idx, sample in eligible:
        # Find the least-assigned compatible flaw
        compatible = [f for f in _FLAW_TYPES if _is_flaw_compatible(f, sample)]
        if not compatible:
            continue
        # Pick the flaw with the lowest count among compatible ones
        compatible.sort(key=lambda f: flaw_counts[f])
        chosen = compatible[0]
        flaw_counts[chosen] += 1
        assigned.append((idx, sample, chosen))

    return assigned


# ---------------------------------------------------------------------------
# Process one sample
# ---------------------------------------------------------------------------


def process_one(
    idx: int,
    sample: dict,
    flaw: str,
) -> dict | None:
    """Generate a DPO pair for one sample.

    Returns the DPO row dict, or None if generation/judge verification failed.
    """
    messages = sample["messages"]
    meta = sample.get("meta", {})

    # Extract system, user, chosen
    system_msg = messages[0]["content"]
    user_msg = messages[1]["content"]
    chosen_content = messages[2]["content"]

    register = meta.get("register", "factual")
    passages = _extract_passages(user_msg)

    # Build prompt context
    prompt = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]

    # Generate rejected — up to 3 tries
    gen_prompt = _build_gen_prompt(
        flaw, system_msg, user_msg, chosen_content, register, passages,
    )
    gen_messages = [
        {"role": "system", "content": GEN_SYSTEM},
        {"role": "user", "content": gen_prompt},
    ]

    rejected: str | None = None
    for attempt in range(MAX_GEN_RETRIES):
        result = _call_dsv4(gen_messages, temperature=0.7, max_tokens=1024)
        if result is None:
            print(
                f"  [idx={idx}] gen attempt {attempt+1} failed (API error)",
                file=sys.stderr, flush=True,
            )
            continue

        # Verify flaw with judge
        judge_system, judge_template = JUDGE_PROMPTS[flaw]
        judge_question = judge_template.format(
            content=result,
            user_question=user_msg,
            register=register,
            passages=passages,
        )
        verdict = _call_judge(judge_system, judge_question)
        if verdict == "YES":
            rejected = result
            break

        print(
            f"  [idx={idx}] flaw '{flaw}' not detected "
            f"(judge={verdict}), attempt {attempt+1}/{MAX_GEN_RETRIES}",
            file=sys.stderr, flush=True,
        )

        # Also verify chosen does NOT exhibit the flaw (once)
        if attempt == 0:
            chosen_verdict = _call_judge(
                judge_system,
                judge_template.format(
                    content=chosen_content,
                    user_question=user_msg,
                    register=register,
                    passages=passages,
                ),
            )
            if chosen_verdict == "YES":
                print(
                    f"  [idx={idx}] WARNING: chosen answer also exhibits flaw "
                    f"'{flaw}' — will still try to generate a rejected variant",
                    file=sys.stderr, flush=True,
                )

    if rejected is None:
        print(
            f"  [idx={idx}] SKIP: failed to generate rejected with flaw '{flaw}' "
            f"after {MAX_GEN_RETRIES} attempts",
            file=sys.stderr, flush=True,
        )
        return None

    # Clean _src_idx from output
    row = {
        "prompt": prompt,
        "chosen": [{"role": "assistant", "content": chosen_content}],
        "rejected": [{"role": "assistant", "content": rejected}],
        "meta": {
            "flaw": flaw,
            "register": register,
            "intent_id": meta.get("intent_id", "?"),
            "_src_idx": idx,
        },
    }
    return row


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    random.seed(42)

    # Load input samples
    samples: list[dict] = []
    with open(INPUT_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                samples.append(json.loads(line))
    print(f"Loaded {len(samples)} samples from {INPUT_PATH}", flush=True)

    # Eligible: all samples except pure refusals
    # (no_context is included since we can still generate most flaw types)
    eligible = [
        (i, s) for i, s in enumerate(samples)
        if s.get("meta", {}).get("sample_type") in ("context", "no_context", None, "")
    ]
    print(f"Eligible samples: {len(eligible)} (excluding refusals)", flush=True)

    # Assign flaw types respecting compatibility
    assigned = _assign_flaws(eligible)
    print(f"Assigned flaws to {len(assigned)} samples", flush=True)

    # Flaw distribution summary
    flaw_counts: dict[str, int] = {}
    for _, _, f in assigned:
        flaw_counts[f] = flaw_counts.get(f, 0) + 1
    print("Assigned flaw distribution:")
    for f, c in sorted(flaw_counts.items()):
        print(f"  {f}: {c}", flush=True)

    # Load checkpoint
    completed = _load_checkpoint()
    print(f"Already completed: {len(completed)} pairs", flush=True)

    # Determine which assigned items remain
    all_indices = [idx for idx, _, _ in assigned]
    todo = [(idx, s, f) for idx, s, f in assigned if idx not in completed]

    # Shuffle for robustness
    random.shuffle(todo)

    print(f"Remaining: {len(todo)} pairs to generate", flush=True)

    if not todo:
        print("Nothing to do — all pairs already completed.", flush=True)
        _assemble_final(completed, all_indices)
        total = len(completed)
        print(f"\nDone! {total} pairs written to {OUTPUT_PATH}", flush=True)
        return

    # Process in batches with concurrency
    batch_size = CONCURRENCY
    total_batches = (len(todo) + batch_size - 1) // batch_size
    batch_num = 0

    while todo and len(completed) < TARGET_PAIRS:
        batch = todo[:batch_size]
        todo = todo[batch_size:]
        batch_label = f"{batch_num+1}/{total_batches}"
        print(f"\nBatch {batch_label} ({len(batch)} pairs, "
              f"{len(completed)} done so far)", flush=True)

        def _process_one(item: tuple[int, dict, str]) -> tuple[int, dict | None]:
            idx, sample, flaw = item
            return idx, process_one(idx, sample, flaw)

        with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
            futures = {pool.submit(_process_one, item): item[0] for item in batch}
            for future in as_completed(futures):
                idx, row = future.result()
                if row is not None:
                    completed[idx] = json.dumps(row, ensure_ascii=False)
                    _save_checkpoint_row(row, f"batch{batch_num:04d}")

        done = len(completed)
        print(f"  Progress: {done} pairs completed", flush=True)

        batch_num += 1

        # If we've generated enough and have some buffer, stop
        if done >= TARGET_PAIRS:
            print(f"  Reached target of {TARGET_PAIRS}+ pairs, stopping.", flush=True)
            break

    # Assemble final output
    _assemble_final(completed, all_indices)
    total = len(completed)

    # Count flaws in final set
    final_flaw_counts: dict[str, int] = {}
    for line in completed.values():
        row = json.loads(line)
        f = row.get("meta", {}).get("flaw", "?")
        final_flaw_counts[f] = final_flaw_counts.get(f, 0) + 1

    print(f"\nDone! {total} pairs written to {OUTPUT_PATH}", flush=True)
    print("Flaw distribution:", flush=True)
    for flaw, count in sorted(final_flaw_counts.items()):
        print(f"  {flaw}: {count}", flush=True)

    if total < TARGET_PAIRS:
        print(
            f"WARNING: only {total} pairs (target {TARGET_PAIRS})",
            file=sys.stderr, flush=True,
        )
        return

    print(f"\nTarget of {TARGET_PAIRS}+ reached. Ready for verification.", flush=True)


if __name__ == "__main__":
    main()
