#!/usr/bin/env python3
"""FT-A2: Generate gold.jsonl — reference answers + gold citations.

Reads finetune/eval/questions.jsonl (256 rows), produces
finetune/eval/gold.jsonl with one entry per question:

    {id, gold_doc_ids[], gold_block_ids[], reference_answer}

For non-negative rows: gold = source blocks from the question;
reference_answer is generated by dsv4 WITH the block text in-context,
≤120 words, names the work by exact title, no bracketed citations.

For negative rows: gold_doc_ids=[], gold_block_ids=[], reference_answer
is a short honest refusal.

Checkpointed & resumable — run under nohup.
"""

from __future__ import annotations

import json
import os
import sys
import time
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

import requests

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO = Path(__file__).resolve().parent.parent
QPATH = REPO / "finetune" / "eval" / "questions.jsonl"
GPATH = REPO / "finetune" / "eval" / "gold.jsonl"
CKPT_DIR = REPO / "finetune" / "eval" / ".gold_checkpoint"
PACK = REPO / "packs" / "library-v1.scpack"
CACHE_DB = REPO / "finetune" / "cache" / "search.db"

LLM_URL = "http://10.0.0.10:8002/v1/chat/completions"
LLM_MODEL = "deepseek-v4-flash"

CONCURRENCY = 8
MAX_RETRIES = 3

# ---------------------------------------------------------------------------
# Corpus access
# ---------------------------------------------------------------------------

def _ensure_corpus_db() -> Path:
    """Extract search.db if needed."""
    if CACHE_DB.exists():
        return CACHE_DB
    CACHE_DB.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(PACK, "r") as zf:
        with zf.open("search.db") as src, open(CACHE_DB, "wb") as dst:
            import shutil
            shutil.copyfileobj(src, dst)
    return CACHE_DB


def _load_doc_titles() -> dict[str, str]:
    """Load doc_id → title from pack manifest."""
    z = zipfile.ZipFile(PACK)
    m = json.loads(z.read("manifest-index.json"))
    items = m if isinstance(m, list) else m.get("docs") or []
    return {d["doc_id"]: d["title"] for d in items}


def _fetch_blocks(doc_blocks: list[tuple[str, str]]) -> dict[tuple[str, str], str]:
    """Fetch block texts from corpus DB.

    Args:
        doc_blocks: list of (doc_id, block_id) tuples.

    Returns:
        dict mapping (doc_id, block_id) → text.
    """
    import sqlite3
    db_path = _ensure_corpus_db()
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    result: dict[tuple[str, str], str] = {}
    try:
        for doc_id, block_id in doc_blocks:
            row = conn.execute(
                "SELECT text FROM blocks WHERE doc_id=? AND block_id=?",
                (doc_id, block_id),
            ).fetchone()
            if row:
                result[(doc_id, block_id)] = row[0]
            else:
                result[(doc_id, block_id)] = ""
    finally:
        conn.close()
    return result


# ---------------------------------------------------------------------------
# Gold row builder
# ---------------------------------------------------------------------------

def _get_gold_spec(q: dict) -> tuple[list[str], list[str]]:
    """Determine (gold_doc_ids, gold_block_ids) for a question.

    For crosswork: use source_doc_ids aligned with source_block_ids.
    For negative: both empty.
    For everything else: source_doc_id + source_block_ids.
    """
    kind = q["kind"]
    if kind == "negative":
        return [], []

    if kind == "crosswork":
        docs = q.get("source_doc_ids", [])
        blocks = q.get("source_block_ids", [])
        # Ensure aligned — spec says docs[i] pairs with blocks[i]
        if len(docs) == len(blocks):
            return docs, blocks
        # Fallback: if crosswork has 2 blocks but docs field has issues,
        # use source_doc_id for the first doc, source_doc_ids for both
        primary = q.get("source_doc_id")
        if primary and docs:
            return [primary, docs[1]] if len(docs) > 1 else [primary], blocks
        return docs, blocks

    # Standard: source_doc_id + source_block_ids
    doc_id = q.get("source_doc_id")
    blocks = q.get("source_block_ids", [])
    if doc_id and blocks:
        return [doc_id] * len(blocks), blocks
    return [], []


# ---------------------------------------------------------------------------
# LLM call
# ---------------------------------------------------------------------------

def _call_dsv4(prompt: str, system: str = "") -> str | None:
    """Call dsv4 with thinking disabled, temp 0.7. Returns content or None."""
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    for attempt in range(MAX_RETRIES):
        try:
            resp = requests.post(
                LLM_URL,
                json={
                    "model": LLM_MODEL,
                    "messages": messages,
                    "temperature": 0.7,
                    "max_tokens": 512,
                    "chat_template_kwargs": {"thinking": False},
                },
                timeout=120,
            )
            if resp.status_code != 200:
                print(f"  [retry {attempt+1}] HTTP {resp.status_code}: {resp.text[:200]}",
                      file=sys.stderr)
                time.sleep(2 * (attempt + 1))
                continue
            data = resp.json()
            content = data.get("choices", [{}])[0].get("message", {}).get("content", "")
            if content:
                return content.strip()
            print(f"  [retry {attempt+1}] empty response", file=sys.stderr)
        except requests.exceptions.Timeout:
            print(f"  [retry {attempt+1}] timeout", file=sys.stderr)
            time.sleep(5)
        except Exception as e:
            print(f"  [retry {attempt+1}] {e}", file=sys.stderr)
            time.sleep(5)
    return None


# ---------------------------------------------------------------------------
# Negative answer builder (no LLM call needed)
# ---------------------------------------------------------------------------

_NEGATIVE_ANSWERS: dict[str, str] = {
    # Medical / medication questions
    "naltrexone": (
        "Our recovery literature does not offer medical advice about naltrexone or any other "
        "medication. These are questions for a doctor or psychiatrist who knows your health history. "
        "The program focuses on the spiritual and emotional dimensions of recovery, not medical treatment."
    ),
    "suboxone": (
        "The recovery literature in our corpus does not address Suboxone or medication-assisted "
        "treatment. These are medical decisions best discussed with your doctor. The Twelve-Step "
        "program welcomes anyone with a desire to stop drinking or using, regardless of medication."
    ),
    "antabuse": (
        "Our literature does not offer medical guidance on Antabuse or other medications. "
        "Please consult a physician for medication-related questions. The program's focus is on "
        "the spiritual principles of recovery, leaving medical matters to professionals."
    ),
    "detox": (
        "Medical detoxification is outside the scope of our recovery literature. Withdrawal from "
        "alcohol or other substances can be medically serious and should be supervised by a healthcare "
        "professional. Please consult a doctor for safe detox guidance."
    ),
    "withdrawal": (
        "Our corpus focuses on the spiritual and emotional aspects of recovery, not medical withdrawal "
        "symptoms or timelines. Withdrawal from alcohol or other substances should be managed under "
        "medical supervision. Please talk to a healthcare provider."
    ),
    "sinclair method": (
        "The Sinclair Method and other medical approaches to alcohol use disorder are not covered in "
        "our recovery literature. The program does not take a position on medical treatments or "
        "harm-reduction methods. These are decisions to make with your doctor."
    ),
    "liver": (
        "Questions about liver recovery and medical test results fall outside the scope of our "
        "recovery literature. Please consult a healthcare professional for medical advice about "
        "liver health. Our program addresses the emotional and spiritual side of recovery."
    ),
    "antidepressant": (
        "Medication interactions and antidepressant use are medical matters not addressed in our "
        "recovery literature. Please consult your doctor or pharmacist for medication guidance. "
        "The program supports whatever medical care you and your physician determine is appropriate."
    ),
    "ibuprofen": (
        "Our literature does not provide medical advice about medication interactions. "
        "Questions about ibuprofen or other medications should be directed to a doctor or pharmacist. "
        "The Twelve-Step program addresses recovery from addiction, not pharmacology."
    ),
    "benzodiazepine": (
        "Benzodiazepine tapering and withdrawal should be managed under medical supervision. "
        "Our recovery literature does not cover medical detoxification protocols. Please consult "
        "a healthcare professional for safe guidance on tapering off benzodiazepines."
    ),
    "suboxone clean time": (
        "Questions about whether medication-assisted treatment counts as clean time are outside "
        "the scope of our literature. The program welcomes anyone with a desire to stop using, "
        "and the relationship between medication and sobriety is a personal matter to discuss "
        "with your sponsor and doctor."
    ),
}

_NEGATIVE_DEFAULT = (
    "Our recovery literature does not address this topic. The materials in our corpus focus on "
    "the Twelve-Step approach to addiction recovery, including the spiritual principles, "
    "emotional growth, and practical tools found in AA/NA and related literature. "
    "For questions outside this scope, please consult the appropriate professional resource."
)


def _build_negative_answer(question: str) -> str:
    """Produce a refusal for a negative-row question."""
    q_lower = question.lower()
    # Check known patterns
    for key, answer in _NEGATIVE_ANSWERS.items():
        if key in q_lower:
            return answer

    # Fallback by question type
    if any(w in q_lower for w in ["doctor", "medical", "medication", "prescribe", "dose",
                                    "dosage", "withdrawal", "detox", "liver", "suboxone",
                                    "naltrexone", "antabuse", "ibuprofen", "antidepressant",
                                    "benzodiazepine"]):
        return _NEGATIVE_ANSWERS["naltrexone"]

    if any(w in q_lower for w in ["laptop", "computer", "wifi", "wi-fi", "car", "rust",
                                    "skillet", "sourdough", "tree sap", "bread"]):
        return _NEGATIVE_DEFAULT

    return _NEGATIVE_DEFAULT


# ---------------------------------------------------------------------------
# Reference answer generation
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = (
    "You are an expert in recovery literature who writes reference answers for evaluating "
    "a RAG system. Your task is to write a concise, accurate answer grounded in the provided "
    "source text(s). Strict rules:\n"
    "1. Answer in natural prose — NO bracketed citations, NO footnotes, NO markdown.\n"
    "2. Name the work(s) by their exact title(s) in the body of the answer.\n"
    "3. Maximum 120 words.\n"
    "4. Do NOT invent details not present in the source texts.\n"
    "5. Do NOT use first-person ('I', 'my', 'we') — write as an authoritative summary.\n"
    "6. Do NOT create fake lived experience.\n"
    "7. Compose a single coherent paragraph."
)


def _build_reference_answer(
    question: str,
    source_texts: list[tuple[str, str, str]],
    titles: dict[str, str],
) -> str | None:
    """Call dsv4 to generate a reference answer given source blocks.

    Args:
        question: The question text.
        source_texts: List of (doc_id, block_id, text) for each gold block.
        titles: doc_id → display title mapping.

    Returns:
        The answer string, or None on failure.
    """
    # Build context block
    context_parts = []
    seen_docs: set[str] = set()
    doc_refs: list[str] = []

    for doc_id, block_id, text in source_texts:
        title = titles.get(doc_id, doc_id)
        if doc_id not in seen_docs:
            doc_refs.append(title)
            seen_docs.add(doc_id)
        context_parts.append(
            f"--- Source: {title} ({doc_id}/{block_id}) ---\n{text}"
        )

    context = "\n\n".join(context_parts)

    prompt = (
        f"Using the following source text(s), write a concise reference answer "
        f"(≤120 words, one paragraph) to the question below.\n\n"
        f"QUESTION: {question}\n\n"
        f"SOURCE TEXTS:\n{context}\n\n"
        f"IMPORTANT: Your answer must name the work(s) by their exact titles "
        f"({', '.join(doc_refs)}) in natural prose. Do not use any bracketed "
        f"citations or markdown. Stay within 120 words."
    )

    return _call_dsv4(prompt, system=_SYSTEM_PROMPT)


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------

def _load_checkpoint() -> dict[str, str]:
    """Load completed entries: id → JSON line. Resumes from previous run."""
    completed: dict[str, str] = {}

    # First, check the checkpoint directory
    if CKPT_DIR.is_dir():
        for ckpt_file in sorted(CKPT_DIR.iterdir()):
            if ckpt_file.suffix == ".jsonl":
                with open(ckpt_file) as f:
                    for line in f:
                        line = line.strip()
                        if line:
                            row = json.loads(line)
                            completed[row["id"]] = line

    # Also load any existing gold.jsonl to avoid re-gen
    if GPATH.is_file():
        with open(GPATH) as f:
            for line in f:
                line = line.strip()
                if line:
                    row = json.loads(line)
                    completed[row["id"]] = line

    return completed


def _save_checkpoint_row(row: dict, batch_id: str):
    """Save a single completed row to a checkpoint file."""
    CKPT_DIR.mkdir(parents=True, exist_ok=True)
    ckpt_file = CKPT_DIR / f"batch_{batch_id}.jsonl"
    with open(ckpt_file, "a") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def _assemble_final(completed: dict[str, str], all_ids: list[str]):
    """Write gold.jsonl from completed entries in the correct order."""
    with open(GPATH, "w") as f:
        for qid in all_ids:
            line = completed.get(qid)
            if line:
                f.write(line + "\n")
            else:
                print(f"WARNING: missing {qid} in completed set", file=sys.stderr)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # Load questions
    questions: list[dict[str, Any]] = []
    with open(QPATH) as f:
        for line in f:
            line = line.strip()
            if line:
                questions.append(json.loads(line))

    print(f"Loaded {len(questions)} questions", flush=True)

    # Load titles
    titles = _load_doc_titles()
    print(f"Loaded {len(titles)} doc titles from manifest", flush=True)

    # Load checkpoint
    completed = _load_checkpoint()
    print(f"Already completed: {len(completed)} rows", flush=True)

    # Determine which questions need generation
    all_ids = [q["id"] for q in questions]
    todo = [q for q in questions if q["id"] not in completed]
    print(f"Remaining: {len(todo)} questions", flush=True)

    if not todo:
        print("Nothing to do — all rows already completed.", flush=True)
        # Still assemble final
        _assemble_final(completed, all_ids)
        print(f"Gold written to {GPATH}", flush=True)
        return

    # Process in batches with concurrency
    batch_size = CONCURRENCY
    total_batches = (len(todo) + batch_size - 1) // batch_size

    for batch_idx in range(total_batches):
        batch = todo[batch_idx * batch_size : (batch_idx + 1) * batch_size]
        batch_label = f"{batch_idx+1}/{total_batches}"
        print(f"\nBatch {batch_label} ({len(batch)} questions)", flush=True)

        def process_one(q: dict) -> tuple[str, dict | None]:
            """Process a single question. Returns (id, gold_row_dict or None)."""
            kind = q["kind"]
            qid = q["id"]
            question = q["question"]

            try:
                gold_doc_ids, gold_block_ids = _get_gold_spec(q)

                if kind == "negative":
                    answer = _build_negative_answer(question)
                    row = {
                        "id": qid,
                        "gold_doc_ids": [],
                        "gold_block_ids": [],
                        "reference_answer": answer,
                    }
                    return qid, row

                # Non-negative: fetch block texts
                doc_block_pairs = list(zip(gold_doc_ids, gold_block_ids))
                texts = _fetch_blocks(doc_block_pairs)

                source_texts: list[tuple[str, str, str]] = []
                for doc_id, block_id in doc_block_pairs:
                    text = texts.get((doc_id, block_id), "")
                    if not text:
                        print(f"  WARN: {qid} — no text for {doc_id}/{block_id}",
                              file=sys.stderr)
                    source_texts.append((doc_id, block_id, text))

                # Generate reference answer
                answer = _build_reference_answer(question, source_texts, titles)
                if answer is None:
                    print(f"  FAIL: {qid} — LLM call failed after retries",
                          file=sys.stderr)
                    return qid, None

                row = {
                    "id": qid,
                    "gold_doc_ids": gold_doc_ids,
                    "gold_block_ids": gold_block_ids,
                    "reference_answer": answer,
                }
                return qid, row

            except Exception as e:
                print(f"  ERROR: {qid} — {e}", file=sys.stderr)
                return qid, None

        # Run batch concurrently
        with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
            futures = {pool.submit(process_one, q): q["id"] for q in batch}
            for future in as_completed(futures):
                qid, row = future.result()
                if row is not None:
                    completed[qid] = json.dumps(row, ensure_ascii=False)
                    _save_checkpoint_row(row, f"batch{batch_idx:04d}")

        # Progress
        done = sum(1 for qid in all_ids if qid in completed)
        print(f"  Progress: {done}/{len(all_ids)}", flush=True)

    # Assemble final gold.jsonl in question order
    _assemble_final(completed, all_ids)
    print(f"\nDone! {len(completed)}/{len(all_ids)} rows written to {GPATH}",
          flush=True)

    # Report any failures
    failed = [qid for qid in all_ids if qid not in completed]
    if failed:
        print(f"FAILED ({len(failed)}): {failed}", file=sys.stderr)


if __name__ == "__main__":
    main()
