#!/usr/bin/env python3
"""FT-D4: DPO training script — QLoRA DPO fine-tune on google/gemma-4-e2b-it.

Starts FROM the SFT adapter (finetune/runs/sft-01/adapter).  Uses TRL's
DPOTrainer with the standard sigmoid DPO loss.

Usage:
    # CPU-side validation (no GPU, no weight downloads):
    python scripts/ft_train_dpo.py \\
        --dataset finetune/gen/dpo.jsonl \\
        --adapter finetune/runs/sft-01/adapter \\
        --dry-run 20

    # Full training (D1 window — GPU allocated to this process):
    python scripts/ft_train_dpo.py \\
        --dataset finetune/gen/dpo.jsonl \\
        --adapter finetune/runs/sft-01/adapter \\
        --config finetune/infra/dpo_config.yaml

    # Override config fields:
    python scripts/ft_train_dpo.py \\
        --dataset finetune/gen/dpo.jsonl \\
        --adapter finetune/runs/sft-01/adapter \\
        --output-dir finetune/runs/dpo-ablation \\
        --learning-rate 5e-6

Dataset schema (JSONL — generated by C4 task):
    Each row is a preference pair:

    {
        "prompt": [{"role":"system","content":"..."},
                   {"role":"user","content":"..."}],
        "chosen": [{"role":"assistant","content":"<grounded, in-voice answer>"}],
        "rejected": [{"role":"assistant","content":"<flawed answer>"}],
        "meta": {
            "flaw": "fake_lived_experience | hotline_when_unneeded |
                     ignores_passages | bracket_citations | rambles"
        }
    }

    C4 generates the pairs; this script validates the schema in dry-run mode.
    When the dataset file does not exist (pre-C4), dummy pairs are fabricated
    with the same schema for validation.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import math
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = REPO_ROOT / "finetune" / "infra" / "dpo_config.yaml"
DEFAULT_OUTPUT = REPO_ROOT / "finetune" / "runs" / "dpo-01"
DEFAULT_ADAPTER = REPO_ROOT / "finetune" / "runs" / "sft-01" / "adapter"


# ---------------------------------------------------------------------------
# Arg parsing
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="DPO QLoRA training for sobriety-copilot (from SFT adapter)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--dataset", required=True,
        help="Path to JSONL DPO pairs (prompt, chosen, rejected, meta.flaw).",
    )
    p.add_argument(
        "--adapter", required=True,
        help="Path to the SFT adapter directory (e.g., finetune/runs/sft-01/adapter).  "
             "Must contain adapter_config.json + adapter_model.safetensors from D3.",
    )
    p.add_argument(
        "--config", default=str(DEFAULT_CONFIG),
        help="Path to YAML config (default: %(default)s).",
    )
    p.add_argument(
        "--output-dir", default=str(DEFAULT_OUTPUT),
        help="Output directory for checkpoints/metrics (default: %(default)s).",
    )
    p.add_argument(
        "--dry-run", nargs="?", const=20, type=int, default=0,
        metavar="N",
        help="CPU-side validation: check config, dataset schema, tokenizer, "
             "and paths — no GPU, no model weights.  Default N=20 steps / "
             "200 samples.  Pass 0 to disable.",
    )
    # Overridable hyperparams
    p.add_argument("--learning-rate", type=float, default=None)
    p.add_argument("--num-epochs", type=float, default=None)
    p.add_argument("--per-device-train-batch-size", type=int, default=None)
    p.add_argument("--gradient-accumulation-steps", type=int, default=None)
    p.add_argument("--max-steps", type=int, default=None)
    p.add_argument("--lr-scheduler-type", default=None)
    p.add_argument("--warmup-ratio", type=float, default=None)
    p.add_argument("--seq-len", type=int, default=None,
                   help="Override sequence length (default: from config, 4096).")
    p.add_argument("--resume-from", type=str, default=None,
                   help="Path to checkpoint dir to resume from.")
    return p


# ---------------------------------------------------------------------------
# Config loader
# ---------------------------------------------------------------------------

def load_config(path: str) -> dict[str, Any]:
    import yaml
    with open(path) as f:
        cfg = yaml.safe_load(f)
    if not isinstance(cfg, dict):
        raise ValueError(
            f"Config {path} must be a top-level dict, got {type(cfg).__name__}"
        )
    return cfg


# ---------------------------------------------------------------------------
# Dataset helpers
# ---------------------------------------------------------------------------

def load_jsonl(path: str, max_rows: int | None = None) -> list[dict]:
    """Load JSONL, optionally limiting to *max_rows*."""
    rows: list[dict] = []
    with open(path) as f:
        for i, line in enumerate(f):
            if max_rows is not None and i >= max_rows:
                break
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


FLAW_CATEGORIES = [
    "fake_lived_experience",
    "hotline_when_unneeded",
    "ignores_passages",
    "bracket_citations",
    "rambles",
]

SYSTEM_PROMPT = (
    "You are a knowledgeable, direct guide to recovery literature. "
    "Answer in two to four short sentences based on the passages provided."
)


def fabricate_dummy_dpo_pairs(count: int = 200) -> list[dict]:
    """Generate schema-identical dummy DPO pairs for CPU-side validation.

    Each pair has a shared prompt (system + user), a chosen (flawless)
    assistant response, and a rejected (flawed) assistant response labeled
    by ``meta.flaw``.

    The schema matches what C4 will produce in finetune/gen/dpo.jsonl.
    No real data is required — all content is synthetic placeholders.
    """
    import random

    user_questions = [
        "How do I work Step One?",
        "What does the Big Book say about resentment?",
        "I'm struggling with the concept of a Higher Power.",
        "How can I make amends when the person won't talk to me?",
        "What is the difference between the steps and the traditions?",
        "I'm having cravings tonight — what should I do?",
        "Can you explain what 'rigorous honesty' means?",
        "Why is prayer mentioned in step eleven?",
    ]

    dummy_chosen_text = (
        "Based on the Big Book, Step One means admitting we were powerless "
        "over alcohol and that our lives had become unmanageable. "  # noqa: E501
        "This is the foundation — without surrender, the other steps cannot work."
    )

    samples: list[dict] = []
    for _ in range(count):
        flaw = random.choice(FLAW_CATEGORIES)
        question = random.choice(user_questions)

        # Build flawed rejected text based on flaw category
        if flaw == "fake_lived_experience":
            rejected_text = (
                "When I was drinking, I used to wake up not knowing where I was. "
                "My sponsor told me to call him every day. [FAKE-LIVED-EXPERIENCE]"
            )
        elif flaw == "hotline_when_unneeded":
            rejected_text = (
                "You should call the suicide hotline right now. " + dummy_chosen_text
            )
        elif flaw == "ignores_passages":
            rejected_text = (
                "I don't need any book to tell me what to do. Just stop drinking — "
                "it's that simple."
            )
        elif flaw == "bracket_citations":
            rejected_text = (
                dummy_chosen_text.replace("Big Book", "[BB]")
                .replace("Step One", "[S1]")
            )
        elif flaw == "rambles":
            rejected_text = (
                "Well, it's complicated because everyone's journey is different "
                "and what works for one person might not work for another and "
                "there are many paths to recovery and you have to find what "
                "works for you personally..."
            )
        else:
            rejected_text = dummy_chosen_text

        samples.append({
            "prompt": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": question},
            ],
            "chosen": [
                {"role": "assistant", "content": dummy_chosen_text},
            ],
            "rejected": [
                {"role": "assistant", "content": rejected_text},
            ],
            "meta": {
                "flaw": flaw,
            },
        })

    return samples


def split_dataset(
    rows: list[dict],
    train_frac: float = 0.98,
    stratify_key: str = "flaw",
) -> tuple[list[dict], list[dict]]:
    """Stratified train/val split by flaw category."""
    import collections

    groups: dict[str, list[dict]] = collections.defaultdict(list)
    for r in rows:
        key = str(r.get("meta", {}).get(stratify_key, "unknown"))
        groups[key].append(r)

    train_all: list[dict] = []
    val_all: list[dict] = []
    for key, group in groups.items():
        group.sort(key=lambda x: json.dumps(x, sort_keys=True))  # deterministic
        n_train = max(1, int(len(group) * train_frac))
        train_all.extend(group[:n_train])
        val_all.extend(group[n_train:])

    # Shuffle deterministically
    import random
    rng = random.Random(42)
    rng.shuffle(train_all)
    rng.shuffle(val_all)
    return train_all, val_all


# ---------------------------------------------------------------------------
# Tokenizer + formatting
# ---------------------------------------------------------------------------

def load_tokenizer(model_name: str):
    """Load tokenizer (config-only — no model weights)."""
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
    )
    return tok


def format_messages(messages: list[dict], tokenizer) -> str:
    """Apply chat template to a list of message dicts."""
    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )


def tokenize_dpo_pair(
    prompt_text: str,
    chosen_text: str,
    rejected_text: str,
    tokenizer,
    seq_len: int,
) -> dict[str, list[int] | list[list[int]]]:
    """Tokenize a single DPO triple (prompt, chosen, rejected).

    Returns a dict with:
        prompt_input_ids, prompt_attention_mask,
        chosen_input_ids, chosen_labels,
        rejected_input_ids, rejected_labels

    Labels mask out the prompt tokens (set to -100) so the loss is computed
    only on the response tokens.
    """
    # Tokenize prompt
    prompt_enc = tokenizer(
        prompt_text,
        truncation=True,
        max_length=seq_len,
        padding=False,
        return_attention_mask=False,
    )
    prompt_ids = prompt_enc["input_ids"]

    # Tokenize chosen response
    chosen_enc = tokenizer(
        chosen_text,
        truncation=True,
        max_length=seq_len - len(prompt_ids),
        padding=False,
        return_attention_mask=False,
    )
    chosen_ids = prompt_ids + chosen_enc["input_ids"]
    chosen_labels = ([-100] * len(prompt_ids)) + chosen_enc["input_ids"]

    # Truncate if needed
    if len(chosen_ids) > seq_len:
        chosen_ids = chosen_ids[:seq_len]
        chosen_labels = chosen_labels[:seq_len]

    # Tokenize rejected response
    rejected_enc = tokenizer(
        rejected_text,
        truncation=True,
        max_length=seq_len - len(prompt_ids),
        padding=False,
        return_attention_mask=False,
    )
    rejected_ids = prompt_ids + rejected_enc["input_ids"]
    rejected_labels = ([-100] * len(prompt_ids)) + rejected_enc["input_ids"]

    if len(rejected_ids) > seq_len:
        rejected_ids = rejected_ids[:seq_len]
        rejected_labels = rejected_labels[:seq_len]

    prompt_attention = [1] * len(prompt_ids)

    return {
        "prompt_input_ids": prompt_ids,
        "prompt_attention_mask": prompt_attention,
        "chosen_input_ids": chosen_ids,
        "chosen_labels": chosen_labels,
        "rejected_input_ids": rejected_ids,
        "rejected_labels": rejected_labels,
    }


# ---------------------------------------------------------------------------
# Dry-run (CPU-side validation)
# ---------------------------------------------------------------------------

def dry_run(args: argparse.Namespace) -> int:
    """Validate everything possible without GPU or model weights.

    Returns 0 on success, 1 on failure.
    """
    import time
    t0 = time.time()
    errors: list[str] = []

    n_steps = args.dry_run
    n_samples = n_steps * 10  # 10 samples per step as a representative batch
    print(f"[dry-run] Validation mode: {n_steps} steps / {n_samples} samples")
    print(f"[dry-run] Config: {args.config}")
    print(f"[dry-run] Dataset: {args.dataset}")
    print(f"[dry-run] Adapter: {args.adapter}")
    print(f"[dry-run] Output dir: {args.output_dir}")

    # ---- 1. Config parsing ----
    print("\n--- 1. Config parsing ---")
    try:
        cfg = load_config(args.config)
        print(f"  Model: {cfg['model']['name']}")
        print(f"  QLoRA r={cfg['qlora']['r']}, alpha={cfg['qlora']['lora_alpha']}")
        dpo_cfg = cfg.get("dpo", {})
        print(f"  DPO beta={dpo_cfg.get('beta', '??')}")
        print(f"  DPO loss_type={dpo_cfg.get('loss_type', '??')}")
        print(f"  Seq len: {cfg['training']['sequence_length']}")
        print(f"  Packing: {cfg['training']['packing']}")
        print(f"  LR: {cfg['training']['learning_rate']}, "
              f"schedule: {cfg['training']['lr_scheduler_type']}")
        print(f"  Warmup ratio: {cfg['training']['warmup_ratio']}")
        print(f"  Eval strategy: {cfg['evaluation']['eval_strategy']}, "
              f"steps={cfg['evaluation']['eval_steps']}")
        print(f"  Stratify by: {cfg.get('dataset', {}).get('stratify_by', 'flaw')}")
        print(f"  Output dir: {cfg.get('output_dir', args.output_dir)}")
        print(f"  OK — config parses cleanly")
    except Exception as e:
        errors.append(f"Config parsing failed: {e}")

    # ---- 2. Output directory ----
    print("\n--- 2. Output directory ---")
    out = Path(args.output_dir)
    try:
        out.mkdir(parents=True, exist_ok=True)
        test_file = out / ".d4_dry_run_test"
        test_file.write_text("ok")
        test_file.unlink()
        print(f"  Output dir {out} exists and is writable")
    except Exception as e:
        errors.append(f"Output dir {out} not writable: {e}")

    # ---- 3. Checkpoint directory logic ----
    print("\n--- 3. Checkpoint directory logic ---")
    checkpoint_dir = out / "checkpoint"
    try:
        checkpoint_dir.mkdir(parents=True, exist_ok=True)
        test_file = checkpoint_dir / ".d4_dry_run_test"
        test_file.write_text("ok")
        test_file.unlink()
        print(f"  Checkpoint dir {checkpoint_dir} works")
        if args.resume_from:
            rp = Path(args.resume_from)
            if rp.is_dir():
                print(f"  Resume-from path {rp} exists")
            else:
                errors.append(f"Resume-from path {rp} does not exist")
    except Exception as e:
        errors.append(f"Checkpoint dir logic failed: {e}")

    # ---- 4. Adapter path plumbing ----
    print("\n--- 4. Adapter path ---")
    adapter_path = Path(args.adapter)
    if adapter_path.is_dir():
        required_files = ["adapter_config.json", "adapter_model.safetensors"]
        present = [f.name for f in adapter_path.iterdir()]
        missing = [f for f in required_files if f not in present]
        if missing:
            print(f"  WARNING: Adapter dir exists but missing files: {missing}")
            print(f"    (expected once D3 GPU run completes)")
        else:
            print(f"  Adapter path {adapter_path} is complete")
    else:
        print(f"  Adapter path {adapter_path} does not exist yet")
        print(f"    (expected — D3 GPU run must complete first)")
    print(f"  Path plumbing validated")

    # ---- 5. Tokenizer loads (config-only) ----
    print("\n--- 5. Tokenizer (config-only, no weights) ---")
    try:
        model_name = cfg["model"]["name"]
        tok = load_tokenizer(model_name)
        seq_len = args.seq_len or cfg["training"]["sequence_length"]
        print(f"  Model: {model_name}")
        print(f"  Tokenizer: {tok.__class__.__name__}")
        print(f"  Vocab size: {tok.vocab_size}")
        print(f"  EOS token: {tok.eos_token_id} "
              f"({tok.decode(tok.eos_token_id) if tok.eos_token_id is not None else 'N/A'})")
        print(f"  Pad token: {tok.pad_token_id}")
        print(f"  Chat template: {'present' if tok.chat_template else 'absent'}")
        # Apply chat template to dummy messages
        dummy_msg = [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Hello?"},
        ]
        formatted = tok.apply_chat_template(
            dummy_msg, tokenize=False, add_generation_prompt=False
        )
        print(f"  Chat template output ({len(formatted)} chars): "
              f"{formatted[:80]}...")
        print(f"  OK — tokenizer loaded and chat template works")
    except Exception as e:
        errors.append(f"Tokenizer loading failed: {e}")

    # ---- 6. Dataset loading + schema validation ----
    print("\n--- 6. Dataset loading ---")
    try:
        ds_path = Path(args.dataset)
        if ds_path.is_file():
            rows = load_jsonl(args.dataset, max_rows=n_samples)
            print(f"  Loaded {len(rows)} rows from {args.dataset}")
        else:
            print(f"  Dataset {args.dataset} not found — fabricating "
                  f"{n_samples} dummy DPO pairs")
            rows = fabricate_dummy_dpo_pairs(n_samples)

        # Schema check
        for i, r in enumerate(rows):
            if "prompt" not in r:
                errors.append(f"Row {i}: missing 'prompt' key")
                continue
            if "chosen" not in r:
                errors.append(f"Row {i}: missing 'chosen' key")
                continue
            if "rejected" not in r:
                errors.append(f"Row {i}: missing 'rejected' key")
                continue

            # Validate prompt structure
            prompt = r["prompt"]
            if not isinstance(prompt, list) or len(prompt) < 1:
                errors.append(f"Row {i}: prompt must be a non-empty list of messages")
            else:
                roles = [m.get("role") for m in prompt]
                if "assistant" in roles:
                    errors.append(f"Row {i}: prompt should not contain assistant messages")

            # Validate chosen/rejected structure
            for field in ("chosen", "rejected"):
                val = r[field]
                if not isinstance(val, list) or len(val) < 1:
                    errors.append(f"Row {i}: {field} must be a list with ≥1 message")
                else:
                    for m in val:
                        if m.get("role") != "assistant":
                            errors.append(f"Row {i}: {field}[].role must be 'assistant'")
                        if "content" not in m or not m["content"]:
                            errors.append(f"Row {i}: {field}[].content missing or empty")
                        if "assistant" in m["content"] and not m["content"].startswith("[DUMMY"):
                            # Just a len check — not strict
                            pass

            # Validate meta.flaw
            meta = r.get("meta", {})
            flaw = meta.get("flaw")
            if flaw not in FLAW_CATEGORIES:
                errors.append(f"Row {i}: meta.flaw must be one of {FLAW_CATEGORIES}, "
                              f"got '{flaw}'")

        if errors:
            print(f"  Schema check FAILED")
        else:
            print(f"  Schema check OK — {len(rows)} rows valid")

        # Stats
        flaws = set()
        for r in rows:
            f = r.get("meta", {}).get("flaw")
            if f:
                flaws.add(f)
        print(f"  Flaw categories: {', '.join(sorted(flaws))}")
        print(f"  Unique: {len(flaws)} / {len(FLAW_CATEGORIES)}")

    except Exception as e:
        errors.append(f"Dataset loading failed: {e}")

    # ---- 7. Formatting + tokenization ----
    print(f"\n--- 7. Tokenization + formatting (seq_len={seq_len}) ---")
    try:
        # Format prompt, chosen, rejected via chat template
        for i, row in enumerate(rows[:50]):  # sample first 50
            prompt_text = format_messages(row["prompt"], tok)
            chosen_text = format_messages(row["chosen"], tok)
            rejected_text = format_messages(row["rejected"], tok)

            result = tokenize_dpo_pair(
                prompt_text, chosen_text, rejected_text, tok, seq_len
            )

            # Sanity checks on first row
            if i == 0:
                n_prompt = len(result["prompt_input_ids"])
                n_chosen = len(result["chosen_input_ids"])
                n_rejected = len(result["rejected_input_ids"])
                print(f"  Sample 0:")
                print(f"    Prompt tokens: {n_prompt}")
                print(f"    Chosen tokens: {n_chosen}")
                print(f"    Rejected tokens: {n_rejected}")
                print(f"    Chosen label mask: "
                      f"{sum(1 for l in result['chosen_labels'] if l != -100)} "
                      f"response tokens / {n_chosen} total")

                # Verify labels mask prompt
                n_masked = sum(1 for l in result["chosen_labels"] if l == -100)
                if n_masked == n_prompt:
                    print(f"    Label masking OK — prompt tokens masked")
                else:
                    errors.append(
                        f"Label masking: expected {n_prompt} masked, "
                        f"got {n_masked}"
                    )

        total = min(len(rows), 50)
        print(f"  Formatted and tokenized {total} pairs")
        print(f"  Tokenization OK")
    except Exception as e:
        errors.append(f"Tokenization/formatting failed: {e}")

    # ---- 8. Stratified split ----
    print(f"\n--- 8. Stratified train/val split ---")
    try:
        train_frac = cfg.get("dataset", {}).get("train_val_split", 0.98)
        stratify_key = cfg.get("dataset", {}).get("stratify_by", "flaw")
        train_rows, val_rows = split_dataset(rows, train_frac, stratify_key)
        print(f"  Train: {len(train_rows)} rows, "
              f"Val: {len(val_rows)} rows "
              f"({train_frac*100:.0f}/{100-train_frac*100:.0f} split)")

        train_flaws = {r["meta"]["flaw"] for r in train_rows if "meta" in r}
        val_flaws = {r["meta"]["flaw"] for r in val_rows if "meta" in r}
        only_val = val_flaws - train_flaws
        if only_val:
            print(f"  WARNING: {len(only_val)} flaws ONLY in validation set: "
                  f"{only_val}")
        print(f"  Train flaws: {len(train_flaws)}, "
              f"Val flaws: {len(val_flaws)}, "
              f"Overlap: {len(train_flaws & val_flaws)}")
    except Exception as e:
        errors.append(f"Stratified split failed: {e}")

    # ---- 9. Argparse override validation ----
    print("\n--- 9. Argparse override validation ---")
    try:
        override_fields = []
        if args.learning_rate:
            override_fields.append(f"lr={args.learning_rate}")
        if args.num_epochs:
            override_fields.append(f"epochs={args.num_epochs}")
        if args.max_steps:
            override_fields.append(f"max_steps={args.max_steps}")
        if args.lr_scheduler_type:
            override_fields.append(f"scheduler={args.lr_scheduler_type}")
        if args.seq_len:
            override_fields.append(f"seq_len={args.seq_len}")
        if override_fields:
            print(f"  CLI overrides: {', '.join(override_fields)}")
        else:
            print(f"  No CLI overrides — using config defaults")
        print(f"  All argparse paths validate")
    except Exception as e:
        errors.append(f"Argparse validation failed: {e}")

    # ---- Summary ----
    elapsed = time.time() - t0
    print(f"\n{'='*60}")
    if errors:
        print(f"DRY-RUN FAILED — {len(errors)} error(s)")
        for e in errors:
            print(f"  • {e}")
        return 1
    else:
        print(f"DRY-RUN PASSED — {elapsed:.1f}s, all CPU-side checks OK")
        print(f"Ready for GPU training in a D1 window.")
        return 0


# ---------------------------------------------------------------------------
# Full training (requires GPU in D1 window)
# ---------------------------------------------------------------------------

def train(args: argparse.Namespace, cfg: dict) -> int:
    """Run the full DPO training pipeline.

    NOTE: This function allocates GPU memory.  Only call inside a D1 window
          (after freeing at least one GPU from vLLM).
    """
    import torch
    from datasets import Dataset as HFDataset
    from peft import LoraConfig, PeftModel
    from transformers import (
        AutoModelForCausalLM,
        AutoTokenizer,
        BitsAndBytesConfig,
    )
    from trl import DPOConfig, DPOTrainer

    model_name = cfg["model"]["name"]
    qlora_cfg = cfg["qlora"]
    dpo_cfg = cfg.get("dpo", {})
    train_cfg = cfg["training"]
    eval_cfg = cfg["evaluation"]
    log_cfg = cfg["logging"]
    ckpt_cfg = cfg["checkpointing"]
    ds_cfg = cfg.get("dataset", {})
    output_dir = args.output_dir
    seq_len = args.seq_len or train_cfg["sequence_length"]
    seed = cfg.get("seed", 42)

    # ---- Load tokenizer ----
    print(f"Loading tokenizer: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # ---- Load dataset ----
    print(f"Loading dataset: {args.dataset}")
    rows = load_jsonl(args.dataset)
    train_frac = ds_cfg.get("train_val_split", 0.98)
    stratify_key = ds_cfg.get("stratify_by", "flaw")
    train_rows, val_rows = split_dataset(rows, train_frac, stratify_key)
    print(f"  Train: {len(train_rows)}, Val: {len(val_rows)}")

    def format_row(
        row: dict,
    ) -> dict[str, str]:
        prompt_text = tokenizer.apply_chat_template(
            row["prompt"], tokenize=False, add_generation_prompt=False
        )
        chosen_text = tokenizer.apply_chat_template(
            row["chosen"], tokenize=False, add_generation_prompt=False
        )
        rejected_text = tokenizer.apply_chat_template(
            row["rejected"], tokenize=False, add_generation_prompt=False
        )
        return {
            "prompt": prompt_text,
            "chosen": chosen_text,
            "rejected": rejected_text,
        }

    train_data = [format_row(r) for r in train_rows]
    val_data = [format_row(r) for r in val_rows]
    train_ds = HFDataset.from_list(train_data)
    val_ds = HFDataset.from_list(val_data)

    # ---- QLoRA bitsandbytes config ----
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=getattr(
            torch, qlora_cfg.get("bnb_4bit_compute_dtype", "bfloat16")
        ),
        bnb_4bit_quant_type=qlora_cfg.get("bnb_4bit_quant_type", "nf4"),
        bnb_4bit_use_double_quant=qlora_cfg.get("bnb_4bit_use_double_quant", True),
    )

    # ---- Load base model in 4-bit ----
    print(f"Loading base model (4-bit NF4): {model_name}")
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=getattr(torch, cfg["model"].get("torch_dtype", "bfloat16")),
        attn_implementation=cfg["model"].get(
            "attn_implementation", "flash_attention_2"
        ),
        trust_remote_code=True,
    )

    # ---- Load SFT adapter ----
    print(f"Loading SFT adapter: {args.adapter}")
    model = PeftModel.from_pretrained(
        model,
        args.adapter,
        is_trainable=True,
    )

    # ---- LoRA config (for reference model) ----
    lora_config = LoraConfig(
        r=qlora_cfg["r"],
        lora_alpha=qlora_cfg["lora_alpha"],
        target_modules=qlora_cfg.get("target_modules"),
        lora_dropout=qlora_cfg.get("lora_dropout", 0.05),
        bias="none",
        task_type="CAUSAL_LM",
        modules_to_save=qlora_cfg.get("modules_to_save"),
        use_dora=qlora_cfg.get("use_dora", False),
        init_lora_weights=qlora_cfg.get("init_lora_weights", True),
    )

    # ---- DPO config ----
    max_steps = (
        args.max_steps if args.max_steps is not None
        else train_cfg.get("max_steps", -1)
    )
    num_epochs = (
        args.num_epochs if args.num_epochs is not None
        else train_cfg.get("num_train_epochs", 3)
    )
    lr = (
        args.learning_rate if args.learning_rate is not None
        else train_cfg.get("learning_rate", 1e-5)
    )
    lr_scheduler = args.lr_scheduler_type or train_cfg.get(
        "lr_scheduler_type", "cosine"
    )

    dpo_config = DPOConfig(
        output_dir=output_dir,
        # Training
        per_device_train_batch_size=(
            args.per_device_train_batch_size
            or train_cfg.get("per_device_train_batch_size", 2)
        ),
        gradient_accumulation_steps=(
            args.gradient_accumulation_steps
            or train_cfg.get("gradient_accumulation_steps", 4)
        ),
        num_train_epochs=num_epochs,
        max_steps=max_steps,
        learning_rate=lr,
        lr_scheduler_type=lr_scheduler,
        warmup_ratio=train_cfg.get("warmup_ratio", 0.1),
        weight_decay=train_cfg.get("weight_decay", 0.01),
        optim=train_cfg.get("optim", "adamw_torch_fused"),
        gradient_checkpointing=train_cfg.get("gradient_checkpointing", True),
        bf16=train_cfg.get("bf16", True),
        tf32=train_cfg.get("tf32", True),
        max_grad_norm=train_cfg.get("max_grad_norm", 1.0),
        # Sequence (DPO does not use packing)
        max_length=seq_len,
        # DPO-specific
        beta=dpo_cfg.get("beta", 0.15),
        loss_type=dpo_cfg.get("loss_type", "sigmoid"),
        reference_free=dpo_cfg.get("reference_free", False),
        label_smoothing=dpo_cfg.get("label_smoothing", 0.0),
        # Evaluation
        eval_strategy=eval_cfg.get("eval_strategy", "steps"),
        eval_steps=eval_cfg.get("eval_steps", 50),
        eval_on_start=eval_cfg.get("eval_on_start", True),
        per_device_eval_batch_size=(
            eval_cfg.get("per_device_eval_batch_size", 2)
        ),
        # Logging
        logging_strategy=log_cfg.get("logging_strategy", "steps"),
        logging_steps=log_cfg.get("logging_steps", 10),
        report_to=log_cfg.get("report_to", "none"),
        # Checkpointing
        save_strategy=ckpt_cfg.get("save_strategy", "steps"),
        save_steps=ckpt_cfg.get("save_steps", 100),
        save_total_limit=ckpt_cfg.get("save_total_limit", 3),
        load_best_model_at_end=ckpt_cfg.get("load_best_model_at_end", False),
        # Misc
        seed=seed,
        remove_unused_columns=True,
        dataloader_num_workers=2,
        dataloader_pin_memory=True,
    )

    # ---- Trainer ----
    trainer = DPOTrainer(
        model=model,
        ref_model=None,  # DPOTrainer creates ref model internally
        args=dpo_config,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        tokenizer=tokenizer,
        peft_config=lora_config,
    )

    # ---- Checkpoint resume ----
    if args.resume_from:
        print(f"Resuming from checkpoint: {args.resume_from}")
        trainer.train(resume_from_checkpoint=args.resume_from)
    else:
        trainer.train()

    # ---- Save final ----
    print(f"Saving final model to {output_dir}")
    trainer.save_model(output_dir)

    # ---- Log final metrics ----
    metrics_path = Path(output_dir) / "metrics.json"
    log_history = trainer.state.log_history
    with open(metrics_path, "w") as f:
        json.dump(log_history, f, indent=2, default=str)
    print(f"Metrics saved to {metrics_path}")

    return 0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    # Resolve paths
    args.config = str(Path(args.config).resolve())
    args.dataset = str(Path(args.dataset).resolve())
    args.adapter = str(Path(args.adapter).resolve())
    args.output_dir = str(Path(args.output_dir).resolve())

    # ---- Dry-run: CPU-side only ----
    if args.dry_run and args.dry_run > 0:
        return dry_run(args)

    # ---- Full training ----
    cfg = load_config(args.config)
    return train(args, cfg)


if __name__ == "__main__":
    raise SystemExit(main())
