"""Curated recovery-topic taxonomy for the corpus knowledge graph.

Every topic is a node in the graph. A topic "mentions" a chunk when any of its
`terms` occur in that chunk's text. Terms are matched on word boundaries and
are case-insensitive; a trailing ``*`` on the last word matches any suffix
(``resent*`` -> resentment / resentments / resentful / resented). Multi-word
terms match the words in order, separated by any non-word run (so ``self pity``
also matches "self-pity").

Bump TAXONOMY_VERSION whenever this file changes so the on-disk graph cache is
rebuilt.
"""

from __future__ import annotations

TAXONOMY_VERSION = 4

# Group id -> human label. Order here is the order the UI shows the legend.
GROUPS: list[tuple[str, str]] = [
    ("steps", "The Steps & Traditions"),
    ("principles", "Spiritual Principles"),
    ("struggles", "Struggles & Defects"),
    ("practices", "Daily Practices"),
    ("fellowship", "Fellowship & Service"),
    ("relationships", "Family & Relationships"),
    ("mind", "Mind, Body & Trauma"),
    ("recovery", "Addiction & Recovery"),
]

# (id, label, group, blurb, terms)
TOPICS: list[tuple[str, str, str, str, list[str]]] = [
    # ── The Steps & Traditions ──────────────────────────────────────────
    ("step_1", "Step One", "steps", "Admitting powerlessness; life had become unmanageable",
     ["step one", "step 1", "first step", "the first step", "we admitted we were powerless"]),
    ("step_2", "Step Two", "steps", "Came to believe a Power greater than ourselves could restore us",
     ["step two", "step 2", "second step", "came to believe", "restore us to sanity"]),
    ("step_3", "Step Three", "steps", "A decision to turn our will and lives over to the care of God as we understood Him",
     ["step three", "step 3", "third step", "turn our will", "turned our will", "god as we understood"]),
    ("step_4", "Step Four", "steps", "A searching and fearless moral inventory",
     ["step four", "step 4", "fourth step", "moral inventory", "searching and fearless"]),
    ("step_5", "Step Five", "steps", "Admitting the exact nature of our wrongs to God, ourselves, and another human being",
     ["step five", "step 5", "fifth step", "exact nature of our wrongs", "another human being"]),
    ("step_6", "Step Six", "steps", "Entirely ready to have God remove all these defects of character",
     ["step six", "step 6", "sixth step", "entirely ready"]),
    ("step_7", "Step Seven", "steps", "Humbly asked Him to remove our shortcomings",
     ["step seven", "step 7", "seventh step", "remove our shortcomings", "humbly asked"]),
    ("step_8", "Step Eight", "steps", "A list of all persons we had harmed, and willingness to make amends",
     ["step eight", "step 8", "eighth step", "persons we had harmed", "list of all persons"]),
    ("step_9", "Step Nine", "steps", "Direct amends wherever possible, except when to do so would injure",
     ["step nine", "step 9", "ninth step", "direct amends", "would injure them"]),
    ("step_10", "Step Ten", "steps", "Continued personal inventory; promptly admitting when wrong",
     ["step ten", "step 10", "tenth step", "promptly admitted", "spot check inventory", "spot-check"]),
    ("step_11", "Step Eleven", "steps", "Prayer and meditation to improve conscious contact",
     ["step eleven", "step 11", "eleventh step", "conscious contact", "knowledge of his will"]),
    ("step_12", "Step Twelve", "steps", "A spiritual awakening; carrying the message; practicing these principles",
     ["step twelve", "step 12", "twelfth step", "twelve step work", "twelfth-step", "practice these principles"]),
    ("traditions", "The Twelve Traditions", "steps", "How groups stay unified, autonomous, and focused on the primary purpose",
     ["tradition one", "tradition two", "tradition three", "tradition four", "tradition five", "tradition six",
      "tradition seven", "tradition eight", "tradition nine", "tradition ten", "tradition eleven", "tradition twelve",
      "twelve traditions", "the traditions", "common welfare", "group conscience", "primary purpose",
      "self-supporting", "self supporting", "outside issues"]),

    # ── Spiritual Principles ────────────────────────────────────────────
    ("honesty", "Honesty", "principles", "Rigorous honesty with ourselves and others",
     ["honest*", "rigorous honesty", "truthful*", "cash register honesty"]),
    ("hope", "Hope", "principles", "Belief that things can get better",
     ["hope", "hopes", "hopeful*", "hopeless*"]),
    ("faith", "Faith", "principles", "Trust in a Power greater than ourselves",
     ["faith", "faith in", "trust in god", "trust god", "believe in god", "belief in god"]),
    ("courage", "Courage", "principles", "Doing the next right thing despite fear",
     ["courage*", "brave*", "the courage to change"]),
    ("humility", "Humility", "principles", "Seeing ourselves as we really are",
     ["humility", "humble", "humbly", "humbled", "humbling"]),
    ("willingness", "Willingness", "principles", "Being willing to go to any lengths",
     ["willing*", "any lengths", "open to change"]),
    ("acceptance", "Acceptance", "principles", "Accepting life on life's terms",
     ["acceptance", "accept*", "life on life's terms", "things i cannot change"]),
    ("surrender", "Surrender", "principles", "Letting go and letting God",
     ["surrender*", "let go and let god", "letting go", "let go", "turn it over", "turned it over"]),
    ("gratitude", "Gratitude", "principles", "A grateful heart never drinks",
     ["gratitude", "grateful*", "thankful*", "gratitude list"]),
    ("forgiveness", "Forgiveness", "principles", "Forgiving others and ourselves",
     ["forgiv*", "forgave", "forgiven"]),
    ("love", "Love & Compassion", "principles", "Love, kindness, and compassion in action",
     ["love", "loving", "loved", "compassion*", "kindness", "tolerance"]),
    ("patience", "Patience & Tolerance", "principles", "Easy does it",
     ["patience", "patient with", "easy does it", "tolerance", "tolerant"]),
    ("serenity", "Serenity & Peace", "principles", "The peace that comes from acceptance",
     ["serenity", "serene", "peace of mind", "inner peace", "at peace", "calm*", "serenity prayer"]),
    ("open_mindedness", "Open-Mindedness", "principles", "Honesty, open-mindedness, and willingness",
     ["open-minded*", "open minded*", "open mind", "closed mind", "prejudice*", "contempt prior to investigation"]),

    # ── Struggles & Defects ─────────────────────────────────────────────
    ("resentment", "Resentment", "struggles", "The number one offender",
     ["resent*", "grudge*", "number one offender", "bitterness"]),
    ("fear", "Fear", "struggles", "An evil and corroding thread",
     ["fear", "fears", "feared", "fearful*", "afraid", "terrified", "dread*", "corroding thread"]),
    ("anger", "Anger", "struggles", "Anger, rage, and irritability",
     ["anger", "angry", "rage", "enraged", "furious", "irritab*", "hostility", "hostile"]),
    ("shame", "Shame", "struggles", "The feeling that we are fundamentally flawed",
     ["shame", "ashamed", "shameful", "shaming", "humiliat*"]),
    ("guilt", "Guilt", "struggles", "Remorse for what we have done",
     ["guilt*", "remorse*", "regret*", "conscience"]),
    ("self_pity", "Self-Pity", "struggles", "Poor me, poor me, pour me a drink",
     ["self pity", "self-pity", "pity", "poor me", "victim*", "martyr*"]),
    ("selfishness", "Selfishness & Self-Centeredness", "struggles", "The root of our troubles",
     ["selfish*", "self-centered*", "self centered*", "self-seeking", "self seeking", "self-will", "self will",
      "root of our troubles", "self-centred*"]),
    ("ego", "Ego & Pride", "struggles", "The bondage of self",
     ["ego", "egotism", "egotistic*", "pride", "prideful", "arrogan*", "grandios*", "bondage of self", "vanity"]),
    ("dishonesty", "Dishonesty & Denial", "struggles", "Lying to ourselves and others",
     ["dishonest*", "lying", "lied", "liar*", "deceit*", "deceiv*", "denial", "self-deception", "self deception",
      "rationaliz*", "justif*"]),
    ("isolation", "Isolation & Loneliness", "struggles", "Terminal uniqueness and the walls we build",
     ["isolat*", "lonel*", "alone", "withdrawn", "cut off from", "terminal uniqueness", "disconnect*"]),
    ("perfectionism", "Perfectionism", "struggles", "Progress, not perfection",
     ["perfection*", "perfectionis*", "progress not perfection", "progress rather than perfection", "never good enough"]),
    ("control", "Control & Letting Go", "struggles", "Trying to run the show",
     ["controlling", "control over", "in control", "out of control", "loss of control", "manipulat*",
      "run the show", "running the show", "control everything", "control others", "controlling others"]),
    ("jealousy", "Jealousy & Envy", "struggles", "Wanting what others have",
     ["jealous*", "envy", "envious", "covet*"]),
    ("grief", "Grief & Loss", "struggles", "Mourning what and whom we have lost",
     ["grief", "grieve", "grieving", "grieved", "mourn*", "bereave*", "loss of a", "died", "death of"]),
    ("depression", "Depression & Despair", "struggles", "The pit of despair and hopelessness",
     ["depress*", "despair*", "hopeless*", "suicid*", "misery", "miserable", "melanchol*"]),
    ("anxiety", "Anxiety & Worry", "struggles", "Living in the wreckage of the future",
     ["anxiety", "anxious*", "worry", "worried", "worrying", "worries", "panic*", "nervous*", "apprehens*"]),

    # ── Daily Practices ─────────────────────────────────────────────────
    ("prayer", "Prayer", "practices", "Talking to a Higher Power",
     ["pray", "prayer*", "prayed", "praying", "thy will be done", "thy will not mine"]),
    ("meditation", "Meditation", "practices", "Listening for guidance",
     ["meditat*", "quiet time", "mindful*", "contemplat*", "stillness", "breathing"]),
    ("inventory", "Personal Inventory", "practices", "Taking stock of ourselves",
     ["inventory", "inventories", "taking stock", "self-examination", "self examination", "self-appraisal",
      "fearless", "moral inventory", "character defects", "defects of character", "shortcomings"]),
    ("amends", "Making Amends", "practices", "Repairing the harm we caused",
     ["amend", "amends", "restitution", "make it right", "harm we had done", "harmed", "wreckage of our past",
      "clean up the wreckage"]),
    ("sponsorship", "Sponsorship", "practices", "Working with a sponsor",
     ["sponsor*", "sponsee*"]),
    ("meetings", "Meetings", "practices", "Where the fellowship gathers",
     ["meeting", "meetings", "home group", "ninety meetings", "90 meetings", "keep coming back",
      "share at", "chairperson", "speaker meeting"]),
    ("one_day", "One Day at a Time", "practices", "Just for today",
     ["one day at a time", "just for today", "twenty-four hours", "twenty four hours", "24 hours",
      "day at a time", "for today", "today i will", "today i can"]),
    ("writing", "Writing & Journaling", "practices", "Putting it on paper",
     ["write down", "writing down", "wrote down", "journal*", "pen to paper", "on paper", "workbook",
      "write it down", "write out", "writing out", "write a list", "write about", "writing about",
      "writing exercise*", "write your"]),
    ("self_care", "Self-Care", "practices", "HALT: hungry, angry, lonely, tired",
     ["self-care", "self care", "halt", "hungry angry lonely", "sleep", "exercise", "nutrition",
      "take care of yourself", "take care of myself", "taking care of myself", "taking care of ourselves",
      "get enough rest", "eat well", "eating well"]),
    ("boundaries", "Boundaries", "practices", "Where I end and you begin",
     ["boundar*", "limits", "say no", "saying no", "setting limits", "detach*"]),
    ("present", "Living in the Present", "practices", "This moment is all we have",
     ["present moment", "the present", "here and now", "this moment", "living in the now",
      "living in the past", "one moment at a time", "in the moment", "the past is", "the here and now"]),

    # ── Fellowship & Service ────────────────────────────────────────────
    ("fellowship", "Fellowship", "fellowship", "We can do together what we cannot do alone",
     ["fellowship", "the group", "our group", "the rooms", "other alcoholics", "other addicts", "members",
      "we are not alone", "together we", "belong*", "community"]),
    ("newcomers", "Newcomers", "fellowship", "The most important person in the room",
     ["newcomer*", "new member*", "new man", "new person", "beginner*", "first meeting", "first days",
      "early recovery", "early sobriety", "first year"]),
    ("service", "Service & Carrying the Message", "fellowship", "Working with others; you have to give it away to keep it",
     ["service", "carry the message", "carrying the message", "carry this message", "working with others",
      "help others", "helping others", "helping another", "give it away", "twelfth step call", "twelve step call",
      "sponsoring", "volunteer*", "be of service"]),
    ("anonymity", "Anonymity", "fellowship", "The spiritual foundation of all our traditions",
     ["anonymity", "spiritual foundation", "principles before personalities", "press radio and films",
      "personal anonymity", "remain anonymous", "anonymous at the level"]),
    ("history", "A.A. History & Founders", "fellowship", "Bill W., Dr. Bob, and how it all began",
     ["bill w", "bill wilson", "dr. bob", "dr bob", "doctor bob", "akron", "oxford group", "ebby", "lois",
      "towns hospital", "founder*", "the big book", "1935", "1939", "sam shoemaker", "silkworth", "carl jung",
      "rowland", "hank p", "ruth hock", "general service", "the conference", "anne smith", "sister ignatia"]),

    # ── Family & Relationships ──────────────────────────────────────────
    ("family", "Family", "relationships", "The family afterward",
     ["family", "families", "parent*", "mother", "father", "children", "child", "household",
      "wives", "wife", "husband", "brother", "sister", "daughter", "son"]),
    ("partners", "Marriage & Partners", "relationships", "Living with someone in recovery",
     ["marriage", "married", "spouse*", "wife", "husband", "partner", "partners", "divorce*", "romantic",
      "relationship with", "girlfriend", "boyfriend", "intimate partner"]),
    ("codependency", "Codependency", "relationships", "Losing ourselves in someone else's problems",
     ["codependen*", "co-dependen*", "caretak*", "caretaking", "rescuing", "rescuer", "enabl*", "people-pleas*",
      "people pleas*", "approval", "obsessed with", "controlling others"]),
    ("acoa", "Adult Children of Alcoholics", "relationships", "Growing up in an alcoholic or dysfunctional home",
     ["adult child*", "acoa", "alcoholic home", "alcoholic parent*", "dysfunctional famil*", "alcoholic famil*",
      "grew up", "growing up", "childhood", "inner child", "abandon*"]),
    ("relationships", "Relationships & Communication", "relationships", "Getting along with people",
     ["relationship*", "communicat*", "conflict*", "argument*", "empath*", "friendship*", "intimacy",
      "get along", "getting along", "other people", "people in our lives"]),
    ("sex", "Sex & Intimacy", "relationships", "Reviewing our sex conduct",
     ["sex", "sexual*", "intimacy", "intimate", "lust", "romance", "sex conduct", "sex life", "infidelity",
      "unfaithful"]),
    ("work", "Work & Money", "relationships", "Employers, careers, and financial wreckage",
     ["employer*", "employee*", "job", "jobs", "career*", "workplace", "money", "financial*", "debt*",
      "boss", "fired", "unemploy*", "paycheck*", "bills", "creditor*", "bankrupt*"]),

    # ── Mind, Body & Trauma ─────────────────────────────────────────────
    ("trauma", "Trauma", "mind", "What happened to you",
     ["trauma*", "ptsd", "post-traumatic", "abuse", "abused", "abusive", "neglect*", "wound*", "flashback*",
      "adverse childhood", "traumatized"]),
    ("body", "The Body & Nervous System", "mind", "The body keeps the score",
     ["nervous system", "the body", "our bodies", "physical symptoms", "immune",
      "cortisol", "adrenal*", "vagus", "heart rate", "physiolog*", "somatic", "sensation*", "hormone*",
      "fight or flight", "fight-or-flight"]),
    ("brain", "Brain & Neuroscience", "mind", "How addiction rewires the brain",
     ["brain*", "dopamine", "neuro*", "prefrontal", "amygdala", "cortex", "receptor*", "serotonin",
      "endorphin*", "opioid receptor", "reward circuit", "neurotransmitter*"]),
    ("emotions", "Emotions & Feelings", "mind", "Feeling our feelings",
     ["emotion*", "feelings", "mood*", "emotional sobriety", "numb*", "feel our feelings", "feel the feelings",
      "painful feelings", "difficult feelings"]),
    ("vulnerability", "Vulnerability & Courage to Be Seen", "mind", "Uncertainty, risk, and emotional exposure",
     ["vulnerab*", "wholehearted*", "daring greatly", "rising strong", "arena", "armor", "authentic*",
      "worthiness", "being seen"]),
    ("self_esteem", "Self-Esteem & Self-Worth", "mind", "Believing we are enough",
     ["self-esteem", "self esteem", "self-worth", "self worth", "self-respect", "self respect", "self-acceptance",
      "self acceptance", "self-love", "self love", "worthy", "unworthy", "not enough", "good enough",
      "self-confidence", "self-compassion", "self compassion", "self-image"]),
    ("stress", "Stress", "mind", "The strain of living",
     ["stress*", "pressure", "overwhelm*", "burnout", "burned out", "tension", "exhaust*"]),
    ("attention", "Attention & ADHD", "mind", "Scattered minds and focus",
     ["attention deficit", "adhd", "hyperactiv*", "distract*", "impulsiv*", "scattered", "concentrat*",
      "inattent*", "attention span"]),
    ("therapy", "Therapy & Counseling", "mind", "Professional help alongside the program",
     ["therap*", "counsel*", "psychiatr*", "psycholog*", "clinician*", "treatment center*", "treatment program*",
      "rehab*", "clients", "patients", "psychotherap*", "in treatment"]),
    ("thinking", "Beliefs & Stinking Thinking", "mind", "The stories we tell ourselves, and how to question them",
     ["stinking thinking", "belief system*", "core belief*", "limiting belief*", "self-talk", "self talk",
      "cognitive", "irrational", "distorted thinking", "negative thinking", "negative thought*",
      "obsessive thinking", "alcoholic thinking", "addictive thinking", "insanity", "insane", "sanity",
      "is it true", "stories we tell", "the story i", "self-deception", "wishful thinking", "magical thinking"]),

    # ── Addiction & Recovery ────────────────────────────────────────────
    ("powerlessness", "Powerlessness & Unmanageability", "recovery", "We could not manage our own lives",
     ["powerless*", "unmanageab*", "lack of power", "could not manage", "cannot manage", "no control",
      "cannot control", "couldn't control", "could not control", "lost control"]),
    ("craving", "Cravings & Obsession", "recovery", "The mental obsession and physical craving",
     ["craving*", "crave*", "obsess*", "compulsion*", "compulsive*", "urge", "urges", "trigger*", "phenomenon of craving",
      "mental obsession", "first drink"]),
    ("relapse", "Relapse", "recovery", "Slips, relapses, and coming back",
     ["relaps*", "slip", "slips", "slipped", "drank again", "drink again", "using again", "went back out",
      "went out", "picked up", "pick up", "drinking again", "came back"]),
    ("bottom", "Hitting Bottom", "recovery", "The gift of desperation",
     ["hit bottom", "hitting bottom", "rock bottom", "hit my bottom", "bottomed out", "my bottom",
      "gift of desperation", "desperat*", "jails institutions", "incomprehensible demoralization",
      "pitiful and incomprehensible", "jail", "prison", "hospital*", "asylum*", "sanitarium"]),
    ("disease", "Alcoholism as Illness", "recovery", "The doctor's opinion; a physical allergy and mental obsession",
     ["disease", "illness", "allergy", "allergic", "malady", "sick", "sickness", "chronic", "progressive",
      "doctor's opinion", "doctors opinion", "medical", "physician*", "fatal", "incurable"]),
    ("drugs", "Drugs & Narcotics", "recovery", "Addiction beyond alcohol",
     ["drug", "drugs", "narcotic*", "heroin", "cocaine", "opiate*", "opioid*", "pills", "marijuana",
      "cannabis", "methamphetamine", "meth", "amphetamine*", "dope", "needle*", "substance*",
      "addict", "addicts", "overdose*", "dealer*", "getting high", "get high"]),
    ("alcohol", "Alcohol & Drinking", "recovery", "King Alcohol and the drinking life",
     ["alcohol", "alcoholism", "drink", "drinks", "drinking", "drank", "drunk*",
      "liquor", "whiskey", "beer", "wine", "booze", "hangover*", "intoxicat*", "sober up", "problem drinker*",
      "hard drinker*", "binge*"]),
    ("withdrawal", "Withdrawal & Detox", "recovery", "Getting the substance out of the body",
     ["withdrawal*", "detox*", "delirium tremens", "d.t.s", "dts", "the shakes", "shaking", "sweats",
      "tremors", "seizure*", "hangover*", "dry out", "drying out", "dried out"]),
    ("awakening", "Spiritual Awakening", "recovery", "A personality change sufficient to bring about recovery",
     ["spiritual awakening", "spiritual experience", "awakening", "awakened", "personality change",
      "psychic change", "white light", "vital spiritual", "transform*", "rebirth", "reborn", "new life",
      "educational variety"]),
    ("promises", "The Promises", "recovery", "We will know a new freedom and a new happiness",
     ["the promises", "new freedom", "new happiness", "will not regret the past", "shut the door on it",
      "serenity and we will know peace", "intuitively know", "materialize", "sometimes quickly sometimes slowly",
      "we will comprehend the word serenity"]),
    ("higher_power", "Higher Power", "recovery", "God as we understood Him",
     ["higher power", "god", "god's", "power greater than", "power greater than ourselves", "creator",
      "as we understood him", "spirit of the universe", "divine", "providence", "the almighty", "our maker",
      "great reality", "infinite power", "loving god", "spiritual", "spirituality", "religio*", "agnostic*",
      "atheist*"]),
    ("sobriety", "Sobriety & Clean Time", "recovery", "Staying sober, one day at a time",
     ["sober", "sobriety", "clean", "clean time", "clean and sober", "abstinen*", "abstain*", "stay sober",
      "staying sober", "stayed sober", "got sober", "years sober", "days sober", "anniversar*", "birthday",
      "chip", "medallion", "sober date", "staying clean"]),
    ("stories", "Personal Stories", "recovery", "What we were like, what happened, and what we are like now",
     ["my story", "our stories", "personal stor*", "what it was like", "what happened", "what we are like now",
      "my first drink", "my drinking", "my using", "i grew up", "i drank", "i used", "my bottom",
      "my sobriety", "my recovery", "my sponsor", "my last drink", "my first meeting"]),
    ("emotional_sobriety", "Emotional Sobriety", "recovery", "Beyond the dry drunk",
     ["emotional sobriety", "dry drunk", "white knuckle", "white-knuckle", "restless irritable and discontent",
      "restless, irritable", "irritable and discontent", "untreated alcoholism", "emotional balance",
      "next frontier"]),
    ("smart", "SMART & CBT Tools", "recovery", "Rational, evidence-based recovery tools",
     ["smart recovery", "abc tool", "abcs", "cost benefit", "cost-benefit", "disputing", "irrational belief*",
      "rational emotive", "cbt", "cognitive behavio*", "stages of change", "hierarchy of values",
      "change plan", "urge log", "vaci", "lifestyle balance", "self-management", "self-empower*",
      "4-point", "four-point", "facilitator*"]),
    ("mate", "Addiction & Society", "recovery", "Hungry ghosts, the myth of normal, and the roots of addiction",
     ["hungry ghost*", "myth of normal", "toxic culture", "societal", "capitalis*",
      "downtown eastside", "vancouver", "indigenous", "poverty", "homeless*", "stigma*", "criminaliz*",
      "harm reduction", "war on drugs", "public health", "drug polic*", "decriminaliz*"]),
]


def topic_ids() -> list[str]:
    return [t[0] for t in TOPICS]
